# Use a lightweight base image
FROM alpine:latest

# Install Docker CLI
RUN apk --no-cache add docker

# Set the working directory inside the container
WORKDIR /app

# Pull the latest Docker image from Docker Hub
ARG DOCKER_IMAGE=j808544j/threadly-frontend:latest
RUN docker pull $DOCKER_IMAGE

# Run the Docker image
CMD ["docker", "run", "-d", "-p", "3000:5147", "$DOCKER_IMAGE"]
